# Generated by Django 2.1.5 on 2021-06-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=250, unique=True)),
                ('device_ip', models.CharField(max_length=15, unique=True)),
                ('serial_number', models.CharField(max_length=250)),
                ('device_type', models.CharField(max_length=20)),
                ('device_add', models.CharField(max_length=5)),
                ('main_door', models.CharField(max_length=15)),
                ('device_port', models.CharField(max_length=10)),
            ],
        ),
    ]
