# Generated by Django 3.2.4 on 2022-02-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_second', models.CharField(max_length=60)),
                ('pin', models.IntegerField()),
                ('card_id', models.IntegerField()),
                ('verified', models.CharField(max_length=60)),
                ('door_name', models.CharField(max_length=60)),
                ('event_type', models.CharField(max_length=60)),
                ('in_out_state', models.CharField(max_length=60)),
                ('device_ip', models.CharField(max_length=60)),
            ],
        ),
    ]
