# Generated by Django 3.2.4 on 2021-11-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Door_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_number', models.IntegerField(max_length=10)),
                ('name_door', models.CharField(max_length=250, unique=True)),
                ('device_name', models.CharField(max_length=250)),
                ('driver_time', models.IntegerField(max_length=300)),
                ('detector_time', models.IntegerField(max_length=300)),
                ('inter_time', models.IntegerField(max_length=300)),
                ('sensor_type', models.CharField(max_length=250)),
            ],
        ),
    ]
