# Generated by Django 3.2.4 on 2021-11-24 05:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0002_door_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door_setting',
            name='detector_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='door_setting',
            name='door_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='door_setting',
            name='driver_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='door_setting',
            name='inter_time',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quantum.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
