# Generated by Django 3.2.4 on 2022-02-25 11:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0003_rename_transaction_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_id',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quantum.devices'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='id_table',
            name='access_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='quantum.access_control'),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='quantum.department'),
        ),
        migrations.CreateModel(
            name='Main_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('in_out_state', models.CharField(max_length=60)),
                ('door_name', models.CharField(max_length=60)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quantum.user_list')),
            ],
        ),
        migrations.CreateModel(
            name='Door_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('in_out_state', models.CharField(max_length=60)),
                ('door_name', models.CharField(max_length=60)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='quantum.user_list')),
            ],
        ),
    ]
