# Generated by Django 3.2.4 on 2021-12-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0003_auto_20211124_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_name', models.CharField(max_length=250, unique=True)),
                ('lock_control', models.CharField(max_length=250)),
                ('time_zone', models.CharField(max_length=250)),
            ],
        ),
    ]
