# Generated by Django 3.2.4 on 2021-12-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0004_access_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True)),
                ('department_id', models.IntegerField(blank=True)),
                ('access_id', models.IntegerField(blank=True)),
                ('device_id', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('images', models.BinaryField(blank=True)),
                ('surname', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('department_id', models.IntegerField()),
                ('card_number', models.CharField(max_length=50)),
                ('access_id', models.CharField(max_length=150)),
            ],
        ),
    ]
