# Generated by Django 3.2.4 on 2022-02-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0004_auto_20220225_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access_id',
            old_name='device_id',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='door_report',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='id_table',
            old_name='access_id',
            new_name='access',
        ),
        migrations.RenameField(
            model_name='main_report',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user_list',
            old_name='department_id',
            new_name='department',
        ),
    ]
