# Generated by Django 3.2.4 on 2022-02-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0005_auto_20220225_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='door_report',
            name='check_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main_report',
            name='check_time',
            field=models.TimeField(default='14:20:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='door_report',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
