# Generated by Django 3.2.4 on 2022-01-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0005_id_table_user_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id_table',
            name='access_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='id_table',
            name='department_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='id_table',
            name='device_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='id_table',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
