# Generated by Django 3.2.4 on 2022-03-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0006_auto_20220225_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='door_report',
            name='user_pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main_report',
            name='user_pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='door_report',
            name='check_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='door_report',
            name='data',
            field=models.DateField(),
        ),
    ]
