# Generated by Django 3.2.4 on 2022-03-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0008_smena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smena',
            name='smena_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
