# Generated by Django 3.2.4 on 2022-03-24 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0009_alter_smena_smena_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door_report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantum.user_list'),
        ),
        migrations.AlterField(
            model_name='main_report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quantum.user_list'),
        ),
    ]
