# Generated by Django 3.2.4 on 2022-01-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0009_door_setting_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='door_setting',
            old_name='device_id',
            new_name='device_ip',
        ),
    ]
