# Generated by Django 3.2.4 on 2022-01-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0010_rename_device_id_door_setting_device_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.IntegerField(blank=True, null=True)),
                ('device_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15)),
                ('user_card', models.CharField(max_length=50)),
                ('access_lock', models.CharField(max_length=15)),
                ('device_ip', models.CharField(max_length=30)),
                ('status_access', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='id_table',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='id_table',
            name='status_access',
        ),
    ]
