# Generated by Django 3.2.4 on 2022-04-16 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0011_remove_id_table_department_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grafik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('grafik_name', models.CharField(max_length=60, unique=True)),
                ('smena', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='quantum.smena')),
            ],
        ),
    ]
