# Generated by Django 3.2.4 on 2022-04-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0013_alter_grafik_smena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grafik',
            name='grafik_name',
            field=models.CharField(max_length=60),
        ),
    ]
