# Generated by Django 3.2.4 on 2022-04-23 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0015_auto_20220422_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_list',
            name='grafik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quantum.grafik'),
        ),
    ]
