# Generated by Django 3.2.4 on 2022-04-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0016_user_list_grafik'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_list',
            name='start_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_list',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
