# Generated by Django 3.2.4 on 2022-05-04 07:45

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0017_auto_20220426_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название Отдела'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quantum.department', verbose_name='Родительская категория'),
        ),
    ]
