# Generated by Django 3.2.4 on 2022-06-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0018_auto_20220504_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='images',
            field=models.TextField(blank=True),
        ),
    ]
