# Generated by Django 3.2.4 on 2022-06-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quantum', '0020_alter_user_list_grafik'),
    ]

    operations = [
        migrations.AddField(
            model_name='door_setting',
            name='keep_open_time',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
